# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "dribia/driworkflows*"
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: ":arrow_up:"

  - package-ecosystem: "uv"
    target-branch: "main"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
        dependency-name: "pyyaml"
      - dependency-type: "direct"
        dependency-name: "pydantic-settings"
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: ":arrow_up:"
    versioning-strategy: "lockfile-only"

  - package-ecosystem: "uv"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "pyyaml"
      - dependency-name: "pydantic-settings"
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: ":arrow_up:"
    versioning-strategy: "increase"
