name: Bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'
        default: 'patch'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    outputs:
      new-version: ${{ steps.bump.outputs.new-version }}
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Bump version
        id: bump
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          make bump-version COMMIT_VERSION=${{ github.event.inputs.version }}
          NEW_VERSION=v$(uv version --dry-run --short)
          git tag -d "$NEW_VERSION" 2> /dev/null
          echo "::add-mask::$NEW_VERSION"
          echo "new-version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
      - name: Push branch
        uses: ad-m/github-push-action@master
        with:
          branch: release/${{ steps.bump.outputs.new-version }}

  create-pull-request:
    needs: [bump-version]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: 'write'
      contents: 'write'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v7
        with:
          ref: release/${{ needs.bump-version.outputs.new-version }}
      - name: Generate token for release bot
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          client-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: ":label: Version bump to ${{ needs.bump-version.outputs.new-version }}"
          base: ${{ github.ref_name }}
          branch: release/${{ needs.bump-version.outputs.new-version }}
          delete-branch: true
          title: ":label: Version bump to ${{ needs.bump-version.outputs.new-version }}"
          reviewers: ${{ github.actor }}
