name: Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    if: contains(github.event.head_commit.message, 'dribia/release/v') && contains(github.event.head_commit.message, '-merge')
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get release tag
        id: get-tag
        run: |
          TAG=$(echo "${{ github.event.head_commit.message }}" | head -n1 | cut -d"/" -f3 | cut -d"-" -f1);
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          tag_name: ${{ steps.get-tag.outputs.tag }}
          draft: true
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
